name: WarpSuite
version: 1.0
main: net.npwdev.candor.warpsuite.WarpSuite
api-version: 1.21

commands:
    warpsuite:
        description: WarpSuite command.
        usage: /warpsuite <set|del|warp|list>
        aliases: [ws]
    setdefaultcooldown:
        description: Set the default cooldown for warps.
        usage: /setdefaultcooldown <seconds>
        aliases: [setcd]